package collector

import (
    "io/ioutil"
    "path/filepath"
    "gopkg.in/yaml.v2"
)

type kstatConfig struct {
	KstatModules []KstatModule `json:"kstat_modules"`
}

type KstatModule struct {
	ID         string      `json:"id"`
	KstatNames []KstatName `json:"kstat_names"`
}

type KstatName struct {
	ID         string      `json:"id"`
	KstatStats []KstatStat `json:"kstat_stats"`
}

type KstatStat struct {
	ID          string      `json:"id"`
	Suffix      string      `json:"suffix"`
	Type        string      `json:"type"`
	Help        string `json:"help"`
	ScaleFactor float64      `json:"scale_factor"`
	LabelString string `json:"label_string"`
}

var kstatConfigInstance = kstatConfig {
        KstatModules: []KstatModule {
		{ 
			ID: "cpu",
                  	KstatNames: []KstatName {
				{
					ID: "sys",
					KstatStats: []KstatStat {
						{
						ID: "bawrite",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						LabelString: "cpu",
						},
						{
						ID: "bread",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						LabelString: "cpu",
						},
						{
						ID: "dtrace_probes",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						LabelString: "cpu",
						},
						{
						ID: "intr",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						LabelString: "cpu",
						},
						{
						ID: "intrblk",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						LabelString: "cpu",
						},
						{
						ID: "intrthread",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						LabelString: "cpu",
						},
						{
						ID: "lread",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						LabelString: "cpu",
						},
						{
						ID: "lwrite",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						LabelString: "cpu",
						},
						{
						ID: "modload",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						LabelString: "cpu",
						},
						{
						ID: "cpu_ticks_idle",
						Suffix: "total",
						Type: "counter",
						Help: "Ticks the CPU spent in idle mode",
						ScaleFactor: 1,
						LabelString: "cpu",
						},
						{
						ID: "cpu_ticks_kernel",
						Suffix: "total",
						Type: "counter",
						Help: "Ticks the CPU spent in kernel mode",
						ScaleFactor: 1,
						LabelString: "cpu",
						},
						{
						ID: "cpu_ticks_user",
						Suffix: "total",
						Type: "counter",
						Help: "Ticks the CPU spent in user mode",
						ScaleFactor: 1,
						LabelString: "cpu",
						},
						{
						ID: "cpu_ticks_wait",
						Suffix: "total",
						Type: "counter",
						Help: "Ticks the CPU spent in wait  mode",
						ScaleFactor: 1,
						LabelString: "cpu",
						},
						{
						ID: "cpu_nsec_dtrace",
						Suffix: "seconds_total",
						Type: "counter",
						Help: "Seconds the CPU spent in dtrace mode",
						ScaleFactor: 1e-9,
						LabelString: "cpu",
						},
						{
						ID: "cpu_nsec_idle",
						Suffix: "seconds_total",
						Type: "counter",
						Help: "Seconds the CPU spent in idle mode",
						ScaleFactor: 1e-9,
						LabelString: "cpu",
						},
						{
						ID: "cpu_nsec_intr",
						Suffix: "seconds_total",
						Type: "counter",
						Help: "Seconds the CPU spent in interrupt mode",
						ScaleFactor: 1e-9,
						LabelString: "cpu",
						},
						{
						ID: "cpu_nsec_kernel",
						Suffix: "seconds_total",
						Type: "counter",
						Help: "Seconds the CPU spent in kernel mode",
						ScaleFactor: 1e-9,
						LabelString: "cpu",
						},
						{
						ID: "cpu_nsec_user",
						Suffix: "seconds_total",
						Type: "counter",
						Help: "Seconds the CPU spent in user mode",
						ScaleFactor: 1e-9,
						LabelString: "cpu",
						},
						{
						ID: "cpu_load_intr",
						Suffix: "percents",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						LabelString: "cpu",
						},
						{
						ID: "cpumigrate",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						LabelString: "cpu",
						},
						{
						ID: "iowait",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						LabelString: "cpu",
						},
						{
						ID: "nthreads",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						LabelString: "cpu",
						},
						{
						ID: "syscall",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						LabelString: "cpu",
						},
						{
						ID: "sysexec",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						LabelString: "cpu",
						},
						{
						ID: "sysfork",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						LabelString: "cpu",
						},
						{
						ID: "sysread",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						LabelString: "cpu",
						},
						{
						ID: "sysvfork",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						LabelString: "cpu",
						},
						{
						ID: "syswrite",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						LabelString: "cpu",
						},
						{
						ID: "trap",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						LabelString: "cpu",
						},
						{
						ID: "idlethread",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						LabelString: "cpu",
						},
						{
						ID: "inv_swtch",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						LabelString: "cpu",
						},
						{
						ID: "mutex_adenters",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						LabelString: "cpu",
						},
						{
						ID: "xcalls",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						LabelString: "cpu",
						},
					},
				},
	                        { 
					ID: "vm",
					KstatStats: []KstatStat{
						{
						ID: "pgswapin",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "pgswapout",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
                        		},
				},
			},
		},
                { 
			ID: "unix",
                  	KstatNames: []KstatName {
                        	{
					ID: "system_pages",
					KstatStats: []KstatStat{
                                		{
                                		ID: "pagesfree",
                                		Suffix: "total",
                                		Type: "counter",
                                		Help: "",
                                		ScaleFactor: 1,
                                		},
						{
						ID: "pageslocked",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "pagestotal",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "physmem",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
					},
				},
                        	{ 
					ID: "pset",
                          		KstatStats: []KstatStat{
                                		{
						ID: "avenrun_15min",
						Suffix: "percents",
						Type: "counter",
						Help: "15 min CPU load average",
						ScaleFactor: 1,
						},
						{
						ID: "avenrun_5min",
						Suffix: "percents",
						Type: "counter",
						Help: "5 min CPU load average",
						ScaleFactor: 1,
						},
						{
						ID: "avenrun_1min",
						Suffix: "percents",
						Type: "counter",
						Help: "1 min CPU load average",
						ScaleFactor: 1,
						},
						{
						ID: "ncpus",
						Suffix: "total",
						Type: "counter",
						Help: "Number of CPUs presented",
						ScaleFactor: 1,
						},
                        		},
				},
			},
		},
                { 
			ID: "zfs",
                  	KstatNames: []KstatName {
                        	{
					ID: "arcstats",
					KstatStats: []KstatStat{
						{
						ID: "access_skip",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "anon_evictable_data",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "anon_evictable_metadata",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "anon_size",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "arc_meta_limit",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "arc_meta_max",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "arc_meta_min",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "arc_meta_used",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "async_upgrade_sync",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "c",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "c_max",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "c_min",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "compressed_size",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "crtime",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "data_size",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "deleted",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "demand_data_hits",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "demand_data_misses",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "demand_hit_predictive_prefetch",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "demand_hit_prescient_prefetch",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "demand_metadata_hits",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "demand_metadata_misses",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "evict_l2_cached",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "evict_l2_eligible",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "evict_l2_eligible_mfu",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "evict_l2_eligible_mru",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "evict_l2_ineligible",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "evict_l2_skip",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "evict_not_enough",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "evict_skip",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "hash_chain_max",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "hash_chains",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "hash_collisions",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "hash_elements",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "hash_elements_max",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "hdr_size",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "hits",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_abort_lowmem",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_asize",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_bufc_data_asize",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_bufc_metadata_asize",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_cksum_bad",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_data_to_meta_ratio",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_evict_l1cached",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_evict_lock_retry",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_evict_reading",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_feeds",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_free_on_write",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_hdr_size",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_hits",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_io_error",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_log_blk_asize",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_log_blk_avg_asize",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_log_blk_count",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_log_blk_writes",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_mfu_asize",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_misses",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_mru_asize",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_prefetch_asize",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_read_bytes",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_rebuild_asize",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_rebuild_bufs",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_rebuild_bufs_precached",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_rebuild_cksum_lb_errors",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_rebuild_dh_errors",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_rebuild_io_errors",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_rebuild_log_blks",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_rebuild_lowmem",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_rebuild_size",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_rebuild_success",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_rebuild_unsupported",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_rw_clash",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_size",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_write_bytes",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_writes_done",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_writes_error",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_writes_lock_retry",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "l2_writes_sent",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "memory_throttle_count",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "metadata_size",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "mfu_evictable_data",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "mfu_evictable_metadata",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "mfu_ghost_evictable_data",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "mfu_ghost_evictable_metadata",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "mfu_ghost_hits",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "mfu_ghost_size",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "mfu_hits",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "mfu_size",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "misses",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "mru_evictable_data",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "mru_evictable_metadata",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "mru_ghost_evictable_data",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "mru_ghost_evictable_metadata",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "mru_ghost_hits",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "mru_ghost_size",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "mru_hits",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "mru_size",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "mutex_miss",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "other_size",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "overhead_size",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "p",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "prefetch_data_hits",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "prefetch_data_misses",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "prefetch_metadata_hits",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "prefetch_metadata_misses",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "size",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "snaptime",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
						{
						ID: "uncompressed_size",
						Suffix: "total",
						Type: "counter",
						Help: "",
						ScaleFactor: 1,
						},
					},
				},
			},
		},
	},
}

func (config *kstatConfig) init() (error) {
	var (
		err error
	)
	filename, _ := filepath.Abs("./collector/kstat_config.yml")
	yamlFile, err := ioutil.ReadFile(filename)

	if err != nil { return err }

	err = yaml.Unmarshal(yamlFile, &config)
	if err != nil { return err }

	return nil
}
